// app/terms/page.tsx

import Link from 'next/link';
import { Navbar } from '@/components/marketing/Navbar';
import { Footer } from '@/components/marketing/sections';

export default function TermsPage() {
  return (
    <main>
      <Navbar />
      <section className="pt-32 pb-20 bg-white">
        <div className="max-w-3xl mx-auto px-6">

          <h1 className="font-display text-4xl font-800 text-slate-900 mb-2">Terms of Service</h1>
          <p className="text-slate-400 text-sm mb-12">Last updated: March 2026</p>

          <div className="prose prose-slate max-w-none">

            <h2>1. Agreement</h2>
            <p>
              By creating a MarketGrow account or using our services, you agree to these Terms of Service.
              If you do not agree, do not use our services. These terms are governed by Dutch law.
            </p>

            <h2>2. The service</h2>
            <p>
              MarketGrow provides an AI-powered analytics and insights platform for ecommerce entrepreneurs.
              We connect to your sales platforms (Shopify, Bol.com, Amazon, Etsy, WooCommerce) and use AI to
              generate actionable insights and recommendations. The service is provided on a subscription basis.
            </p>

            <h2>3. Account</h2>
            <ul>
              <li>You must be at least 18 years old to use MarketGrow</li>
              <li>You are responsible for keeping your login credentials secure</li>
              <li>You are responsible for all activity that occurs under your account</li>
              <li>You must provide accurate information when creating your account</li>
              <li>One account per person — you may not share accounts</li>
            </ul>

            <h2>4. Subscriptions and billing</h2>
            <ul>
              <li>All plans include a 14-day free trial. No credit card is required to start a trial on the Starter plan</li>
              <li>After the trial, your subscription renews automatically each month</li>
              <li>You can cancel at any time. Your access continues until the end of the current billing period</li>
              <li>Prices are in euros and exclude VAT where applicable</li>
              <li>We reserve the right to change pricing with 30 days notice</li>
              <li>No refunds are provided for partial months</li>
            </ul>

            <h2>5. Acceptable use</h2>
            <p>You may not use MarketGrow to:</p>
            <ul>
              <li>Violate any laws or regulations</li>
              <li>Access or scrape data from third-party platforms in violation of their terms of service</li>
              <li>Attempt to reverse-engineer, hack, or disrupt our services</li>
              <li>Resell or sublicense access to our platform without written permission</li>
              <li>Use the platform for any purpose other than legitimate business analytics</li>
            </ul>

            <h2>6. Data and privacy</h2>
            <p>
              Your use of MarketGrow is also governed by our <Link href="/privacy">Privacy Policy</Link>.
              You retain ownership of your store data. By connecting your platforms to MarketGrow,
              you grant us a limited license to process your data solely for the purpose of providing the service.
            </p>

            <h2>7. AI-generated insights</h2>
            <p>
              The recommendations and insights generated by MarketGrow's AI are based on your data and are
              provided for informational purposes only. They do not constitute financial, legal, or business advice.
              You are solely responsible for decisions made based on these insights.
            </p>

            <h2>8. Service availability</h2>
            <p>
              We aim for high availability but do not guarantee uninterrupted access to the service.
              We may perform maintenance that temporarily affects availability. We will try to notify
              you in advance of planned downtime.
            </p>

            <h2>9. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, MarketGrow's liability is limited to the amount
              you paid for the service in the three months preceding the claim. We are not liable for
              indirect, incidental, or consequential damages.
            </p>

            <h2>10. Termination</h2>
            <p>
              We may suspend or terminate your account if you violate these terms. You may cancel your
              account at any time from your account settings. Upon termination, your data will be deleted
              within 90 days in accordance with our Privacy Policy.
            </p>

            <h2>11. Changes to these terms</h2>
            <p>
              We may update these terms. We will notify you by email at least 30 days before material
              changes take effect. Continued use of the service after changes constitutes acceptance.
            </p>

            <h2>12. Contact</h2>
            <p>
              Questions? Contact us at <a href="mailto:hello@marketgrow.ai">hello@marketgrow.ai</a>.
            </p>

          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}
